# Generated by Django 4.0.5 on 2022-06-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medclinic', '0009_appointment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('tel', models.IntegerField(max_length=11)),
            ],
        ),
    ]
