# Generated by Django 4.0.5 on 2022-06-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medclinic', '0010_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='tel',
            field=models.CharField(max_length=11),
        ),
    ]
